name: Idea
description: Capture an idea
title: "💡 "
labels: ["idea"]
projects: ["keiranking/5"]
body:
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the idea
