backend:
  name: git-gateway
  repo: keiranking/oursbz
  branch: main
  identity_url: https://auth.decapbridge.com/sites/d037644e-743f-4f7a-be2d-ded20d2d79a8
  gateway_url: https://gateway.decapbridge.com
logo_url: images/login-logo.svg
media_folder: "content/images"
public_folder: "/images"
publish_mode: editorial_workflow
search: false
site_url: https://ours.bz
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: ""
collections:
  - name: "playbook"
    label: "Playbook"
    folder: "content/playbook"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "layout", label: "Layout",  widget: "hidden", default: "page" }
      - { name: "body",   label: "Content", widget: "markdown" }
